// "use client"
import "devicon/devicon.min.css";
// import React, { useState } from "react"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Preloader from "@/widgets/LandingPage/Preloader";
import Navbar from "@/components/Navbar/Navbar";
import ScrollHandler from "@/components/ScrollHandler/ScrollHandler.";
import RingCursor from "@/widgets/LandingPage/RingCursor";
import Footer from "@/components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const [loading, setLoading] = useState(true);
  return (
    <html
      lang="en"
      className={`${geistSans.variable} {!loading && ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* <ScrollHandler /> */}
        {/* {!loading && */}
        <RingCursor />
        <section className="relative bg-[radial-gradient(circle_at_center,var(--tw-gradient-stops))] from-[#1a153a] via-[#08051e] to-[#030014]">
          <Navbar />
          {children}
          <Footer />
        </section>
        {/* } */}
      </body>
    </html>
  );
}
